### ISSUE TITLE
What is this plugin for?

### ISSUE THREAD

**Issue by ralsu091** [JetBrains/TeamCity.SESPlugin#14]
I was looking for a plugin that will use SES to send email notifications on build failures. Does this plugin offer this functionality?

Thanks,
Rayan

**Comment by Linfar** [comment]
Hello

Email notifications are part of bundled TeamCity plugins and can be used with or without SES plugin. Please refer to [TeamCity documentation](https://www.jetbrains.com/help/teamcity/subscribing-to-notifications.html#SubscribingtoNotifications-SubscribingtoNotifications) to configure them. 

SES plugin only tracks [email bounces](https://en.wikipedia.org/wiki/Bounce_message) to temporary block sending notifications in case user has marked the notification as spam, has invalid email address, etc. You can use Amazon SES to send email notifications without SES plugin - using SMTP protocol.

**Comment by ralsu091** [comment]
Hi @Linfar, I totally missed it! Thanks for your response.
